version: "3"
services:
  services:
    my-spring:
      image: ghcr.io/integratedproject-int221/back-end:master
      ports: 
        - "3000:3000"
networks:
  default:
    external:
      name: project221
