 version: '3'
 services:
     my-spring:
         build: .
         ports:
          - "3000:3000"
         environment:
                 - DB_HOST=172.17.0.2
                 - DB_USER=root
                 - DB_PASS=THONGtong15444
        



